open Tester
module T = Testtools
module Ex = Exercise.Main

let () = ignore (run_test_case {
      name  = "Ex.2.6(4)";
      func   = Ex.capitalize;
      prep  = T.id;
      ishow = Char.escaped;
      oshow = Char.escaped;
      cmp  = (=);
      dataset = [
          { input = ' '; expected = ' ' };
          { input = '!'; expected = '!' };
          { input = '"'; expected = '"' };
          { input = '#'; expected = '#' };
          { input = '$'; expected = '$' };
          { input = '%'; expected = '%' };
          { input = '&'; expected = '&' };
          { input = '\''; expected ='\'' };
          { input = '('; expected = '(' };
          { input = ')'; expected = ')' };
          { input = '*'; expected = '*' };
          { input = '+'; expected = '+' };
          { input = ','; expected = ',' };
          { input = '-'; expected = '-' };
          { input = '.'; expected = '.' };
          { input = '/'; expected = '/' };
          { input = '0'; expected = '0' };
          { input = '1'; expected = '1' };
          { input = '2'; expected = '2' };
          { input = '3'; expected = '3' };
          { input = '4'; expected = '4' };
          { input = '5'; expected = '5' };
          { input = '6'; expected = '6' };
          { input = '7'; expected = '7' };
          { input = '8'; expected = '8' };
          { input = '9'; expected = '9' };
          { input = ':'; expected = ':' };
          { input = ';'; expected = ';' };
          { input = '<'; expected = '<' };
          { input = '='; expected = '=' };
          { input = '>'; expected = '>' };
          { input = '?'; expected = '?' };
          { input = '@'; expected = '@' };
          { input = 'A'; expected = 'A' };
          { input = 'B'; expected = 'B' };
          { input = 'C'; expected = 'C' };
          { input = 'D'; expected = 'D' };
          { input = 'E'; expected = 'E' };
          { input = 'F'; expected = 'F' };
          { input = 'G'; expected = 'G' };
          { input = 'H'; expected = 'H' };
          { input = 'I'; expected = 'I' };
          { input = 'J'; expected = 'J' };
          { input = 'K'; expected = 'K' };
          { input = 'L'; expected = 'L' };
          { input = 'M'; expected = 'M' };
          { input = 'N'; expected = 'N' };
          { input = 'O'; expected = 'O' };
          { input = 'P'; expected = 'P' };
          { input = 'Q'; expected = 'Q' };
          { input = 'R'; expected = 'R' };
          { input = 'S'; expected = 'S' };
          { input = 'T'; expected = 'T' };
          { input = 'U'; expected = 'U' };
          { input = 'V'; expected = 'V' };
          { input = 'W'; expected = 'W' };
          { input = 'X'; expected = 'X' };
          { input = 'Y'; expected = 'Y' };
          { input = 'Z'; expected = 'Z' };
          { input = '['; expected = '[' };
          { input = '\\'; expected = '\\' };
          { input = ']'; expected = ']' };
          { input = '^'; expected = '^' };
          { input = '_'; expected = '_' };
          { input = '`'; expected = '`' };
          { input = 'a'; expected = 'A' };
          { input = 'b'; expected = 'B' };
          { input = 'c'; expected = 'C' };
          { input = 'd'; expected = 'D' };
          { input = 'e'; expected = 'E' };
          { input = 'f'; expected = 'F' };
          { input = 'g'; expected = 'G' };
          { input = 'h'; expected = 'H' };
          { input = 'i'; expected = 'I' };
          { input = 'j'; expected = 'J' };
          { input = 'k'; expected = 'K' };
          { input = 'l'; expected = 'L' };
          { input = 'm'; expected = 'M' };
          { input = 'n'; expected = 'N' };
          { input = 'o'; expected = 'O' };
          { input = 'p'; expected = 'P' };
          { input = 'q'; expected = 'Q' };
          { input = 'r'; expected = 'R' };
          { input = 's'; expected = 'S' };
          { input = 't'; expected = 'T' };
          { input = 'u'; expected = 'U' };
          { input = 'v'; expected = 'V' };
          { input = 'w'; expected = 'W' };
          { input = 'x'; expected = 'X' };
          { input = 'y'; expected = 'Y' };
          { input = 'z'; expected = 'Z' };
          { input = '{'; expected = '{' };
          { input = '|'; expected = '|' };
          { input = '}'; expected = '}' };
          { input = '~'; expected = '~' };
          { input = '\n'; expected = '\n' };
          { input = '\t'; expected = '\t' };
          { input = '\r'; expected = '\r' };
          { input = '\b'; expected = '\b' };
      ]
})
